### PR TITLE
Allow some projects to not be updated

### PR DESCRIPTION
**Pull request by jcoyne**
But we can continue to merge all of them.

### CODE REVIEW

**Review by justinlittman — APPROVED** [review]

**Comment by jcoyne** [comment]
@mjgiarlo I had no idea that mylibrary was a libsys project and that it used this. I'll update the PR to convert that to yaml too.

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> @mjgiarlo I had no idea that mylibrary was a libsys project and that it used this. I'll update the PR to convert that to yaml too.

OK, cool!

The Access team is short-handed this week (no new hires on board yet, chris on vacation, and me FRing), so can we take another look next week?

**Comment by jcoyne** [comment]
@mjgiarlo I'm not in a rush, this is just a time saver for the FR so they don't have to merge the 4 LD4P updates by hand.

**Review by camillevilla — APPROVED** [review]
🚢 Looks benign to me

**Comment by mjgiarlo** [comment]
@jcoyne If you merge, keep an eye on the Jenkins build?

**Pull request merged**
