### PR TITLE
Move revs-indexer-service to access team

### PR DESCRIPTION
**Pull request by jcoyne**
The repository is tagged as an access team responsibility and listed in the Access team portfolio: https://consul.stanford.edu/display/DSG/DLSS+Software+Portfolios+and+teams

### CODE REVIEW

**Comment by cbeer** [comment]
I think @peetucket needs to weigh in. We moved it over to infrastructure since he seemed to be the sole maintainer of the project.

**Comment by peetucket** [comment]
This is similar to the other indexers (based on discovery_indexer and base-indexer gems), with the revs specific mappings of course.  Rather than based on the team where I am personally sitting, I think it makes sense to either (1) keep it with the same team that the revs project itself is on and/or (2) keep it the other indexers that are similar in nature (e.g. bassi_verrati ?)

**Comment by ndushay** [comment]
@peetucket @jcoyne we should talk about this PR at infradev team meeting Tues Aug 20 -- it seems related to editstore-updater questions.

**Comment by peetucket** [comment]
if we do de-commission the Revs website (which seems likely), the revs-indexer can go away too

**Pull request closed without merging**
