### PR TITLE
Upgrade yarn dependendencies for Ruby/Rails projects

### LINKED ISSUE #127: Add support for yarn

### PR DESCRIPTION
**Pull request by mjgiarlo**
Hi, @sul-dlss/access-team folks! I welcome your feedback on this approach to keeping yarn deps in Rubyland up to date. (Draft for now.) cc: @jcoyne 

Fixes #127 (assuming that's scoped for Ruby/Rails projects, not for replacing npm in JS projects)

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

**Comment by cbeer** [comment]
Can we please get https://github.com/sul-dlss/access-update-scripts/pull/105 in first?

**Comment by mjgiarlo** [comment]
@cbeer :speech_balloon: 
> Can we please get #105 in first?

You bet. I'll rebase, fix conflicts, merge, and kill the ensuing job run this afternoon. Thanks!

**Comment by mjgiarlo** [comment]
@cbeer OK, this is ready for another look. Thanks for reminding me about #105. Much better now.

**Review by mejackreed — APPROVED** [review]
+1 Thanks @mjgiarlo

**Pull request merged**
