### PR TITLE
Separate githubLinks javascript into access & infra varieties

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by jkeck** [comment]
@mjgiarlo cool, I wonder though how you all are using this?  This bit of JS is intended to give you something to copy/paste into the spreadsheet every week.  However; we've fallen into the habit of taking the content that is sent via the slack message to our respective channels and copy/pasting that into the spreadsheet instead.  The format is more-or-less the same between these two and doesn't necessitate a copy of the project list in an additional place.

That being said, if this is working for you all, more power to you. 

Happy to chat about more about this w/ any of y'all. 😁

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team Regarding @jkeck's question :point_up:, are we using the Slack message or the gist to populate the spreadsheet?

**Comment by aaron-collier** [comment]
I've always used the gist

**Comment by mjgiarlo** [comment]
@jkeck so you don't do what's in rows 3 and 4 in the instructions sheet here? https://docs.google.com/spreadsheets/d/12fTiyvn6lz3gkVRyAhttxYua6dYHHSCZ1rJFaAd1X6U/edit#gid=402762120 And for row 5, you copy from Slack instead? if so, I think that'd be an improvement over what is described in the instructions sheet, and it would be great to have both teams adopt this workflow (in favor of needing to maintain a list of portfolio projects in multiple locations).

**Comment by ndushay** [comment]
the one time i did it, I used the gist, but i'm happy to do whatever the instructions say.  Getting rid of stuff is always nice.  :-)

**Comment by jkeck** [comment]
@mjgiarlo That's correct.  Realistically we jump into the process at line 6 and the "string" referenced there is what is coped from the slack message.

**Comment by mjgiarlo** [comment]
@jkeck the way y'all do it sounds better to me. We'll follow suit and I'll close this PR. Thanks!

**Pull request closed without merging**
